import { describe,expect,it } from 'vitest'
import { parseImportSheets } from '../lib/import-products'

describe('catalog import validation',()=>{
  it('parses integer cents and related option sheets',()=>{const result=parseImportSheets({Productos:[['codigo','nombre','descripcion','categoria','precio','activo'],['P1','Pizza','Grande','Pizzas','12500,50','sí']],GruposOpciones:[['producto_codigo','grupo_codigo','nombre','obligatorio','minimo','maximo'],['P1','G1','Tamaño','sí',1,1]],Opciones:[['grupo_codigo','opcion_codigo','nombre','precio_adicional'],['G1','O1','Grande','1500.25']]});expect(result.errors).toEqual([]);expect(result.products[0]?.basePriceCents).toBe(1_250_050);expect(result.options[0]?.priceDeltaCents).toBe(150_025)})
  it('reports invalid and duplicate rows without importing them silently',()=>{const result=parseImportSheets({Productos:[['codigo','nombre','categoria','precio'],['A','Uno','Cat',10],['A','Dos','Cat',20],['','Inválido','Cat',-1]]});expect(result.products).toHaveLength(2);expect(result.errors.join(' ')).toMatch(/duplicado/i);expect(result.errors.join(' ')).toMatch(/obligatorios/i)})
  it('requires the product headers, prices and at least one valid row',()=>{const missingHeaders=parseImportSheets({Productos:[['nombre'],['Sin código']]});expect(missingHeaders.products).toEqual([]);expect(missingHeaders.errors.join(' ')).toMatch(/faltan columnas/i);expect(missingHeaders.errors.join(' ')).toMatch(/al menos una fila/i);const missingPrice=parseImportSheets({Productos:[['codigo','nombre','categoria','precio'],['P1','Pizza','Pizzas','']]});expect(missingPrice.products).toEqual([])})
  it('keeps an empty promotional price as null and rejects present invalid values',()=>{const result=parseImportSheets({Productos:[['codigo','nombre','categoria','precio','precio_promocional'],['EMPTY','Sin promoción','Cat',100,''],['NEGATIVE','Negativo','Cat',100,-1],['TEXT','Texto','Cat',100,'no-es-un-precio'],['TOO_HIGH','Fuera de rango','Cat',100,10_000_000_001]]});expect(result.products).toHaveLength(1);expect(result.products[0]).toMatchObject({code:'EMPTY',promotionalPriceCents:null});expect(result.errors).toEqual(expect.arrayContaining(['Productos fila 3: el precio promocional debe ser un importe válido, no negativo y dentro del límite permitido.','Productos fila 4: el precio promocional debe ser un importe válido, no negativo y dentro del límite permitido.','Productos fila 5: el precio promocional debe ser un importe válido, no negativo y dentro del límite permitido.']))})
  it('rejects unsafe cross-sheet references and negative option prices',()=>{const result=parseImportSheets({Productos:[['codigo','nombre','categoria','precio'],['P1','Pizza','Pizzas',100]],GruposOpciones:[['producto_codigo','grupo_codigo','nombre','minimo','maximo'],['NOPE','G1','Tamaño',0,1],['P1','G2','Salsa',0,1]],Opciones:[['grupo_codigo','opcion_codigo','nombre','precio_adicional'],['G2','O1','Extra',-1]]});expect(result.errors.join(' ')).toMatch(/producto_codigo no existe/i);expect(result.errors.join(' ')).toMatch(/precio no negativo/i)})
  it('rejects a category that cannot produce a database slug',()=>{const result=parseImportSheets({Productos:[['codigo','nombre','categoria','precio'],['P1','Pizza','---',100]]});expect(result.products).toEqual([]);expect(result.errors.join(' ')).toMatch(/categoría debe contener letras o números/i)})
})
