import { useQuery } from '@tanstack/react-query'
import { Building2,CheckCircle2,ClipboardList,ShieldCheck } from 'lucide-react'
import { Link } from 'react-router'
import { z } from 'zod'
import { ErrorPanel,LoadingScreen } from '../../components/Feedback'
import { PageHeader } from '../../components/PageHeader'
import { supabase } from '../../lib/supabase/client'

export function SuperAdminDashboardPage(){const query=useQuery({queryKey:['superadmin-dashboard'],queryFn:async()=>{const[restaurants,orders,members]=await Promise.all([supabase.from('restaurants').select('status'),supabase.from('orders').select('status').gte('created_at',new Date(Date.now()-86400000).toISOString()),supabase.from('restaurant_members').select('status')]);if(restaurants.error||orders.error||members.error)throw new Error('No se pudieron cargar las métricas generales.');return{restaurants:z.array(z.object({status:z.string()})).parse(restaurants.data),orders:z.array(z.object({status:z.string()})).parse(orders.data),members:z.array(z.object({status:z.string()})).parse(members.data)}}});if(query.isLoading)return <LoadingScreen/>;if(query.error)return <ErrorPanel>{query.error.message}</ErrorPanel>;const cards=[['Restaurantes activos',query.data?.restaurants.filter((r)=>r.status==='active').length??0,Building2],['Pedidos 24 h',query.data?.orders.length??0,ClipboardList],['Pedidos tomados',query.data?.orders.filter((o)=>['accepted','completed'].includes(o.status)).length??0,CheckCircle2],['Membresías activas',query.data?.members.filter((m)=>m.status==='active').length??0,ShieldCheck]] as const;return <><PageHeader eyebrow="AAL2 verificado" title="Control central" description="Vista general de la plataforma. Ningún nombre o correo se utiliza como criterio de autorización." actions={<Link className="button-primary" to="/superadmin/restaurantes/nuevo">Crear restaurante</Link>}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,Icon])=><article key={label} className="rounded-3xl border border-slate-800 bg-slate-900 p-5"><Icon className="h-6 w-6 text-orange-400"/><p className="mt-6 text-sm text-slate-400">{label}</p><p className="font-display text-3xl font-bold">{value}</p></article>)}</div></>}
